project:
  type: website

website:
  title: "report-er"
  navbar:
    left:
      - href: report-er.qmd
      
format:
    html:
      toc: true
      code-fold: true
      code-summary: "Code"
      toc-location: left
      toc-title: " "
      theme: [custom.scss]
      include-after-body: "footer.html"
      template-partials:
        - title-block.html
      css: style.css
      smooth-scroll: true
      code-annotations: hover
      title-block-banner: true